name: crudapp
description: A new Flutter project.
 
 
publish_to: 'none'  

 
 
 
 
 
 
 
 
 
 
 
 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

 
 
 
 
 
 
dependencies:
  flutter:
    sdk: flutter
   

   
   
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  velocity_x: ^3.6.0
  provider: ^6.0.5
  flutter_svg: ^1.1.6
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1 
  cloud_firestore: ^4.3.1
  firebase_database: ^10.0.9
  intl: ^0.17.0
  dob_input_field: ^2.0.0
  fluttertoast: ^8.1.3
  image_picker: ^0.8.6+1
  email_auth: ^1.0.0
  chat_gpt_sdk:
    git:
      url: https://github.com/iampawan/Flutter-ChatGPT.git
  flutter_dotenv: ^5.0.2
  selectable: ^0.2.11
  clipboard: ^0.1.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
   
   
   
   
   
  flutter_lints: ^2.0.0

 
 

 
flutter:

   
   
   
  uses-material-design: true

   
  assets:
    - assets/Images/
    - 

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
